import type { ICard } from './types';

export const CARDS: Record<string, ICard> = {
  // CONTEXT CARDS
  'context-basic': {
    id: 'context-basic',
    name: 'Basic Prompt',
    type: 'context',
    energyCost: 1,
    description: 'Simple instruction with minimal context',
    pros: ['Low cost', 'Fast to write', 'Easy to understand'],
    cons: ['Limited accuracy', 'May miss edge cases', 'No examples'],
    bestFor: ['Simple tasks', 'Prototyping', 'Testing'],
    avoidWhen: ['Complex requirements', 'High accuracy needed', 'Ambiguous tasks'],
  },
  'context-detailed': {
    id: 'context-detailed',
    name: 'Detailed Instructions',
    type: 'context',
    energyCost: 2,
    description: 'Comprehensive prompt with clear guidelines and constraints',
    pros: ['Better accuracy', 'Clear expectations', 'Handles edge cases'],
    cons: ['Higher token cost', 'Takes longer to craft', 'May be overfitted'],
    bestFor: ['Production systems', 'Complex tasks', 'Regulated domains'],
    avoidWhen: ['Simple queries', 'Exploratory work', 'Low-stakes tasks'],
  },
  'context-fewshot': {
    id: 'context-fewshot',
    name: 'Few-Shot Examples',
    type: 'context',
    energyCost: 3,
    description: 'Prompt with 3-5 example input/output pairs',
    pros: ['Excellent accuracy', 'Shows exact format', 'Reduces ambiguity'],
    cons: ['High token cost', 'Examples must be perfect', 'Needs maintenance'],
    bestFor: ['Specific formats', 'Classification', 'Style matching'],
    avoidWhen: ['Token limits', 'Highly variable tasks', 'Simple instructions suffice'],
  },
  'context-cot': {
    id: 'context-cot',
    name: 'Chain-of-Thought',
    type: 'context',
    energyCost: 2,
    description: 'Prompt that encourages step-by-step reasoning',
    pros: ['Better logic', 'Transparent thinking', 'Catches errors'],
    cons: ['Slower responses', 'More tokens', 'May overthink simple tasks'],
    bestFor: ['Math problems', 'Complex reasoning', 'Debugging'],
    avoidWhen: ['Speed critical', 'Simple lookups', 'Token constrained'],
  },

  // MODEL CARDS
  'model-gpt4': {
    id: 'model-gpt4',
    name: 'GPT-4',
    type: 'model',
    energyCost: 4,
    description: 'Advanced reasoning, excellent at complex tasks',
    pros: ['Best accuracy', 'Strong reasoning', 'Broad knowledge'],
    cons: ['Most expensive', 'Slower', 'Overkill for simple tasks'],
    bestFor: ['Complex analysis', 'Code generation', 'Creative writing'],
    avoidWhen: ['Budget constrained', 'Simple tasks', 'High volume'],
  },
  'model-gpt35': {
    id: 'model-gpt35',
    name: 'GPT-3.5 Turbo',
    type: 'model',
    energyCost: 2,
    description: 'Fast and cost-effective for most tasks',
    pros: ['Good balance', 'Fast responses', 'Lower cost'],
    cons: ['Less capable than GPT-4', 'Struggles with complex logic', 'Smaller context'],
    bestFor: ['Chat applications', 'Simple queries', 'High volume'],
    avoidWhen: ['Complex reasoning', 'Code generation', 'Nuanced understanding needed'],
  },
  'model-claude': {
    id: 'model-claude',
    name: 'Claude',
    type: 'model',
    energyCost: 3,
    description: 'Excellent at long-form content and analysis',
    pros: ['Large context window', 'Thoughtful responses', 'Good at summarization'],
    cons: ['Can be verbose', 'Medium cost', 'May over-explain'],
    bestFor: ['Document analysis', 'Long conversations', 'Detailed explanations'],
    avoidWhen: ['Need concise answers', 'Budget constrained', 'Simple lookups'],
  },
  'model-llama': {
    id: 'model-llama',
    name: 'LLaMA 2',
    type: 'model',
    energyCost: 1,
    description: 'Open-source model, self-hostable',
    pros: ['No API cost', 'Data privacy', 'Customizable'],
    cons: ['Requires hosting', 'Lower capability', 'Needs fine-tuning'],
    bestFor: ['Privacy-critical', 'Custom domains', 'On-premise'],
    avoidWhen: ['Best accuracy needed', 'No infrastructure', 'Quick prototyping'],
  },

  // TOOL CARDS
  'tool-search': {
    id: 'tool-search',
    name: 'Web Search',
    type: 'tool',
    energyCost: 2,
    description: 'Real-time internet search capability',
    pros: ['Current information', 'Fact checking', 'Broad coverage'],
    cons: ['Can be slow', 'May find wrong info', 'Costs API calls'],
    bestFor: ['Current events', 'Research', 'Fact verification'],
    avoidWhen: ['Static knowledge', 'Speed critical', 'Offline systems'],
  },
  'tool-database': {
    id: 'tool-database',
    name: 'Database Query',
    type: 'tool',
    energyCost: 2,
    description: 'Query internal databases for specific data',
    pros: ['Accurate data', 'Fast lookups', 'Structured results'],
    cons: ['Limited to schema', 'Needs SQL skills', 'Can expose data'],
    bestFor: ['Customer records', 'Transaction history', 'Inventory'],
    avoidWhen: ['Unstructured data', 'No database', 'Privacy concerns'],
  },
  'tool-calculator': {
    id: 'tool-calculator',
    name: 'Calculator',
    type: 'tool',
    energyCost: 1,
    description: 'Precise mathematical calculations',
    pros: ['100% accurate', 'Fast', 'No hallucination'],
    cons: ['Limited to math', 'Requires exact syntax', 'No reasoning'],
    bestFor: ['Math problems', 'Financial calculations', 'Data analysis'],
    avoidWhen: ['Word problems only', 'Approximate answers ok', 'No math needed'],
  },
  'tool-code-exec': {
    id: 'tool-code-exec',
    name: 'Code Execution',
    type: 'tool',
    energyCost: 3,
    description: 'Run Python/JavaScript code in sandbox',
    pros: ['Precise results', 'Data processing', 'Complex logic'],
    cons: ['Security risks', 'Slow', 'Needs validation'],
    bestFor: ['Data transformation', 'Complex calculations', 'Testing'],
    avoidWhen: ['Security critical', 'Simple tasks', 'No sandbox available'],
  },

  // FRAMEWORK CARDS
  'framework-react': {
    id: 'framework-react',
    name: 'ReAct',
    type: 'framework',
    energyCost: 3,
    description: 'Reasoning + Acting framework for step-by-step tasks',
    pros: ['Transparent reasoning', 'Iterative improvement', 'Good for multi-step'],
    cons: ['Can be slow', 'More API calls', 'May loop'],
    bestFor: ['Research tasks', 'Multi-step problems', 'Debugging'],
    avoidWhen: ['Speed critical', 'Simple queries', 'Single-shot tasks'],
  },
  'framework-reflection': {
    id: 'framework-reflection',
    name: 'Self-Reflection',
    type: 'framework',
    energyCost: 2,
    description: 'Agent critiques its own output and improves',
    pros: ['Higher quality', 'Catches errors', 'Self-improving'],
    cons: ['Slower', 'Higher cost', 'Can overthink'],
    bestFor: ['High-stakes outputs', 'Code review', 'Writing'],
    avoidWhen: ['Speed needed', 'Budget tight', 'First draft ok'],
  },
  'framework-sequential': {
    id: 'framework-sequential',
    name: 'Sequential Chain',
    type: 'framework',
    energyCost: 2,
    description: 'Break task into ordered steps',
    pros: ['Clear pipeline', 'Easy to debug', 'Predictable'],
    cons: ['Rigid', 'No backtracking', 'Linear only'],
    bestFor: ['Data pipelines', 'Document processing', 'ETL'],
    avoidWhen: ['Need flexibility', 'Branching logic', 'Interactive tasks'],
  },
  'framework-parallel': {
    id: 'framework-parallel',
    name: 'Parallel Processing',
    type: 'framework',
    energyCost: 4,
    description: 'Process multiple tasks simultaneously',
    pros: ['Very fast', 'Scalable', 'Independent tasks'],
    cons: ['Complex coordination', 'Higher cost', 'Race conditions'],
    bestFor: ['Bulk processing', 'A/B testing', 'Map-reduce'],
    avoidWhen: ['Sequential dependencies', 'Limited budget', 'Order matters'],
  },

  // GUARDRAIL CARDS
  'guardrail-content-filter': {
    id: 'guardrail-content-filter',
    name: 'Content Filter',
    type: 'guardrail',
    energyCost: 1,
    description: 'Block inappropriate or harmful content',
    pros: ['Safety first', 'Brand protection', 'Compliance'],
    cons: ['May block valid content', 'False positives', 'Adds latency'],
    bestFor: ['Public-facing', 'Kids content', 'Regulated industries'],
    avoidWhen: ['Internal tools', 'Trusted users', 'Speed critical'],
  },
  'guardrail-pii-scrubber': {
    id: 'guardrail-pii-scrubber',
    name: 'PII Scrubber',
    type: 'guardrail',
    energyCost: 2,
    description: 'Remove personally identifiable information',
    pros: ['Privacy protection', 'GDPR compliance', 'Security'],
    cons: ['May remove needed data', 'Imperfect detection', 'Processing cost'],
    bestFor: ['Healthcare', 'Finance', 'Customer support'],
    avoidWhen: ['PII needed for task', 'Internal only', 'No sensitive data'],
  },
  'guardrail-fact-check': {
    id: 'guardrail-fact-check',
    name: 'Fact Checker',
    type: 'guardrail',
    energyCost: 3,
    description: 'Verify claims against trusted sources',
    pros: ['Reduces hallucination', 'Trustworthy', 'Quality control'],
    cons: ['Slow', 'Expensive', 'May reject correct but novel info'],
    bestFor: ['News', 'Medical', 'Legal'],
    avoidWhen: ['Creative writing', 'Opinions', 'Speed needed'],
  },
  'guardrail-output-validator': {
    id: 'guardrail-output-validator',
    name: 'Output Validator',
    type: 'guardrail',
    energyCost: 1,
    description: 'Ensure output matches expected format',
    pros: ['Consistent format', 'Catches errors', 'Reliable parsing'],
    cons: ['Rigid structure', 'Rejects valid variations', 'Extra step'],
    bestFor: ['JSON output', 'APIs', 'Structured data'],
    avoidWhen: ['Free-form text', 'Creative output', 'Format flexible'],
  },
};

export const CARD_ARRAY: ICard[] = Object.values(CARDS);
